// Code generated by entc, DO NOT EDIT.

package widget

const (
	// Label holds the string label denoting the widget type in the database.
	Label = "widget"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the widget in the database.
	Table = "widgets"
)

// Columns holds all SQL columns for widget fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
