// Code generated by entc, DO NOT EDIT.

package widgettype

const (
	// Label holds the string label denoting the widgettype type in the database.
	Label = "widget_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the widgettype in the database.
	Table = "widget_types"
)

// Columns holds all SQL columns for widgettype fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
