// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/tmc/moderncrud/ent/widgettype"
)

// WidgetType is the model entity for the WidgetType schema.
type WidgetType struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WidgetType) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case widgettype.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type WidgetType", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WidgetType fields.
func (wt *WidgetType) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case widgettype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			wt.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this WidgetType.
// Note that you need to call WidgetType.Unwrap() before calling this method if this WidgetType
// was returned from a transaction, and the transaction was committed or rolled back.
func (wt *WidgetType) Update() *WidgetTypeUpdateOne {
	return (&WidgetTypeClient{config: wt.config}).UpdateOne(wt)
}

// Unwrap unwraps the WidgetType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wt *WidgetType) Unwrap() *WidgetType {
	tx, ok := wt.config.driver.(*txDriver)
	if !ok {
		panic("ent: WidgetType is not a transactional entity")
	}
	wt.config.driver = tx.drv
	return wt
}

// String implements the fmt.Stringer.
func (wt *WidgetType) String() string {
	var builder strings.Builder
	builder.WriteString("WidgetType(")
	builder.WriteString(fmt.Sprintf("id=%v", wt.ID))
	builder.WriteByte(')')
	return builder.String()
}

// WidgetTypes is a parsable slice of WidgetType.
type WidgetTypes []*WidgetType

func (wt WidgetTypes) config(cfg config) {
	for _i := range wt {
		wt[_i].config = cfg
	}
}
