// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tmc/moderncrud/ent/widgettype"
)

// WidgetTypeCreate is the builder for creating a WidgetType entity.
type WidgetTypeCreate struct {
	config
	mutation *WidgetTypeMutation
	hooks    []Hook
}

// Mutation returns the WidgetTypeMutation object of the builder.
func (wtc *WidgetTypeCreate) Mutation() *WidgetTypeMutation {
	return wtc.mutation
}

// Save creates the WidgetType in the database.
func (wtc *WidgetTypeCreate) Save(ctx context.Context) (*WidgetType, error) {
	var (
		err  error
		node *WidgetType
	)
	if len(wtc.hooks) == 0 {
		if err = wtc.check(); err != nil {
			return nil, err
		}
		node, err = wtc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WidgetTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = wtc.check(); err != nil {
				return nil, err
			}
			wtc.mutation = mutation
			if node, err = wtc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(wtc.hooks) - 1; i >= 0; i-- {
			if wtc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wtc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wtc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (wtc *WidgetTypeCreate) SaveX(ctx context.Context) *WidgetType {
	v, err := wtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wtc *WidgetTypeCreate) Exec(ctx context.Context) error {
	_, err := wtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wtc *WidgetTypeCreate) ExecX(ctx context.Context) {
	if err := wtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wtc *WidgetTypeCreate) check() error {
	return nil
}

func (wtc *WidgetTypeCreate) sqlSave(ctx context.Context) (*WidgetType, error) {
	_node, _spec := wtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (wtc *WidgetTypeCreate) createSpec() (*WidgetType, *sqlgraph.CreateSpec) {
	var (
		_node = &WidgetType{config: wtc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: widgettype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: widgettype.FieldID,
			},
		}
	)
	return _node, _spec
}

// WidgetTypeCreateBulk is the builder for creating many WidgetType entities in bulk.
type WidgetTypeCreateBulk struct {
	config
	builders []*WidgetTypeCreate
}

// Save creates the WidgetType entities in the database.
func (wtcb *WidgetTypeCreateBulk) Save(ctx context.Context) ([]*WidgetType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(wtcb.builders))
	nodes := make([]*WidgetType, len(wtcb.builders))
	mutators := make([]Mutator, len(wtcb.builders))
	for i := range wtcb.builders {
		func(i int, root context.Context) {
			builder := wtcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WidgetTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wtcb *WidgetTypeCreateBulk) SaveX(ctx context.Context) []*WidgetType {
	v, err := wtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wtcb *WidgetTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := wtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wtcb *WidgetTypeCreateBulk) ExecX(ctx context.Context) {
	if err := wtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
