// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tmc/moderncrud/ent/predicate"
	"github.com/tmc/moderncrud/ent/widgettype"
)

// WidgetTypeQuery is the builder for querying WidgetType entities.
type WidgetTypeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WidgetType
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WidgetTypeQuery builder.
func (wtq *WidgetTypeQuery) Where(ps ...predicate.WidgetType) *WidgetTypeQuery {
	wtq.predicates = append(wtq.predicates, ps...)
	return wtq
}

// Limit adds a limit step to the query.
func (wtq *WidgetTypeQuery) Limit(limit int) *WidgetTypeQuery {
	wtq.limit = &limit
	return wtq
}

// Offset adds an offset step to the query.
func (wtq *WidgetTypeQuery) Offset(offset int) *WidgetTypeQuery {
	wtq.offset = &offset
	return wtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wtq *WidgetTypeQuery) Unique(unique bool) *WidgetTypeQuery {
	wtq.unique = &unique
	return wtq
}

// Order adds an order step to the query.
func (wtq *WidgetTypeQuery) Order(o ...OrderFunc) *WidgetTypeQuery {
	wtq.order = append(wtq.order, o...)
	return wtq
}

// First returns the first WidgetType entity from the query.
// Returns a *NotFoundError when no WidgetType was found.
func (wtq *WidgetTypeQuery) First(ctx context.Context) (*WidgetType, error) {
	nodes, err := wtq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{widgettype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wtq *WidgetTypeQuery) FirstX(ctx context.Context) *WidgetType {
	node, err := wtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WidgetType ID from the query.
// Returns a *NotFoundError when no WidgetType ID was found.
func (wtq *WidgetTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wtq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{widgettype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wtq *WidgetTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := wtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WidgetType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one WidgetType entity is not found.
// Returns a *NotFoundError when no WidgetType entities are found.
func (wtq *WidgetTypeQuery) Only(ctx context.Context) (*WidgetType, error) {
	nodes, err := wtq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{widgettype.Label}
	default:
		return nil, &NotSingularError{widgettype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wtq *WidgetTypeQuery) OnlyX(ctx context.Context) *WidgetType {
	node, err := wtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WidgetType ID in the query.
// Returns a *NotSingularError when exactly one WidgetType ID is not found.
// Returns a *NotFoundError when no entities are found.
func (wtq *WidgetTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wtq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = &NotSingularError{widgettype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wtq *WidgetTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := wtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WidgetTypes.
func (wtq *WidgetTypeQuery) All(ctx context.Context) ([]*WidgetType, error) {
	if err := wtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return wtq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (wtq *WidgetTypeQuery) AllX(ctx context.Context) []*WidgetType {
	nodes, err := wtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WidgetType IDs.
func (wtq *WidgetTypeQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := wtq.Select(widgettype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wtq *WidgetTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := wtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wtq *WidgetTypeQuery) Count(ctx context.Context) (int, error) {
	if err := wtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return wtq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (wtq *WidgetTypeQuery) CountX(ctx context.Context) int {
	count, err := wtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wtq *WidgetTypeQuery) Exist(ctx context.Context) (bool, error) {
	if err := wtq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return wtq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (wtq *WidgetTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := wtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WidgetTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wtq *WidgetTypeQuery) Clone() *WidgetTypeQuery {
	if wtq == nil {
		return nil
	}
	return &WidgetTypeQuery{
		config:     wtq.config,
		limit:      wtq.limit,
		offset:     wtq.offset,
		order:      append([]OrderFunc{}, wtq.order...),
		predicates: append([]predicate.WidgetType{}, wtq.predicates...),
		// clone intermediate query.
		sql:  wtq.sql.Clone(),
		path: wtq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WidgetType.Query().
//		GroupBy(widgettype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (wtq *WidgetTypeQuery) GroupBy(field string, fields ...string) *WidgetTypeGroupBy {
	group := &WidgetTypeGroupBy{config: wtq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := wtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return wtq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.WidgetType.Query().
//		Select(widgettype.FieldName).
//		Scan(ctx, &v)
//
func (wtq *WidgetTypeQuery) Select(fields ...string) *WidgetTypeSelect {
	wtq.fields = append(wtq.fields, fields...)
	return &WidgetTypeSelect{WidgetTypeQuery: wtq}
}

func (wtq *WidgetTypeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range wtq.fields {
		if !widgettype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wtq.path != nil {
		prev, err := wtq.path(ctx)
		if err != nil {
			return err
		}
		wtq.sql = prev
	}
	return nil
}

func (wtq *WidgetTypeQuery) sqlAll(ctx context.Context) ([]*WidgetType, error) {
	var (
		nodes = []*WidgetType{}
		_spec = wtq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &WidgetType{config: wtq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, wtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wtq *WidgetTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wtq.querySpec()
	return sqlgraph.CountNodes(ctx, wtq.driver, _spec)
}

func (wtq *WidgetTypeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := wtq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (wtq *WidgetTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   widgettype.Table,
			Columns: widgettype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: widgettype.FieldID,
			},
		},
		From:   wtq.sql,
		Unique: true,
	}
	if unique := wtq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := wtq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, widgettype.FieldID)
		for i := range fields {
			if fields[i] != widgettype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wtq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wtq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wtq *WidgetTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wtq.driver.Dialect())
	t1 := builder.Table(widgettype.Table)
	columns := wtq.fields
	if len(columns) == 0 {
		columns = widgettype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wtq.sql != nil {
		selector = wtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range wtq.predicates {
		p(selector)
	}
	for _, p := range wtq.order {
		p(selector)
	}
	if offset := wtq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wtq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WidgetTypeGroupBy is the group-by builder for WidgetType entities.
type WidgetTypeGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wtgb *WidgetTypeGroupBy) Aggregate(fns ...AggregateFunc) *WidgetTypeGroupBy {
	wtgb.fns = append(wtgb.fns, fns...)
	return wtgb
}

// Scan applies the group-by query and scans the result into the given value.
func (wtgb *WidgetTypeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := wtgb.path(ctx)
	if err != nil {
		return err
	}
	wtgb.sql = query
	return wtgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := wtgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(wtgb.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := wtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) StringsX(ctx context.Context) []string {
	v, err := wtgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wtgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) StringX(ctx context.Context) string {
	v, err := wtgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(wtgb.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := wtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) IntsX(ctx context.Context) []int {
	v, err := wtgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wtgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) IntX(ctx context.Context) int {
	v, err := wtgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(wtgb.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := wtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := wtgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wtgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) Float64X(ctx context.Context) float64 {
	v, err := wtgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(wtgb.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := wtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := wtgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wtgb *WidgetTypeGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wtgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wtgb *WidgetTypeGroupBy) BoolX(ctx context.Context) bool {
	v, err := wtgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wtgb *WidgetTypeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range wtgb.fields {
		if !widgettype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wtgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wtgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wtgb *WidgetTypeGroupBy) sqlQuery() *sql.Selector {
	selector := wtgb.sql.Select()
	aggregation := make([]string, 0, len(wtgb.fns))
	for _, fn := range wtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(wtgb.fields)+len(wtgb.fns))
		for _, f := range wtgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(wtgb.fields...)...)
}

// WidgetTypeSelect is the builder for selecting fields of WidgetType entities.
type WidgetTypeSelect struct {
	*WidgetTypeQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (wts *WidgetTypeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := wts.prepareQuery(ctx); err != nil {
		return err
	}
	wts.sql = wts.WidgetTypeQuery.sqlQuery(ctx)
	return wts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wts *WidgetTypeSelect) ScanX(ctx context.Context, v interface{}) {
	if err := wts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) Strings(ctx context.Context) ([]string, error) {
	if len(wts.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := wts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wts *WidgetTypeSelect) StringsX(ctx context.Context) []string {
	v, err := wts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wts *WidgetTypeSelect) StringX(ctx context.Context) string {
	v, err := wts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) Ints(ctx context.Context) ([]int, error) {
	if len(wts.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := wts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wts *WidgetTypeSelect) IntsX(ctx context.Context) []int {
	v, err := wts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wts *WidgetTypeSelect) IntX(ctx context.Context) int {
	v, err := wts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(wts.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := wts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wts *WidgetTypeSelect) Float64sX(ctx context.Context) []float64 {
	v, err := wts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wts *WidgetTypeSelect) Float64X(ctx context.Context) float64 {
	v, err := wts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(wts.fields) > 1 {
		return nil, errors.New("ent: WidgetTypeSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := wts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wts *WidgetTypeSelect) BoolsX(ctx context.Context) []bool {
	v, err := wts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (wts *WidgetTypeSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{widgettype.Label}
	default:
		err = fmt.Errorf("ent: WidgetTypeSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wts *WidgetTypeSelect) BoolX(ctx context.Context) bool {
	v, err := wts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wts *WidgetTypeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := wts.sql.Query()
	if err := wts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
