// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tmc/moderncrud/ent/predicate"
	"github.com/tmc/moderncrud/ent/widgettype"
)

// WidgetTypeDelete is the builder for deleting a WidgetType entity.
type WidgetTypeDelete struct {
	config
	hooks    []Hook
	mutation *WidgetTypeMutation
}

// Where appends a list predicates to the WidgetTypeDelete builder.
func (wtd *WidgetTypeDelete) Where(ps ...predicate.WidgetType) *WidgetTypeDelete {
	wtd.mutation.Where(ps...)
	return wtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wtd *WidgetTypeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wtd.hooks) == 0 {
		affected, err = wtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WidgetTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wtd.mutation = mutation
			affected, err = wtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wtd.hooks) - 1; i >= 0; i-- {
			if wtd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wtd *WidgetTypeDelete) ExecX(ctx context.Context) int {
	n, err := wtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wtd *WidgetTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: widgettype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: widgettype.FieldID,
			},
		},
	}
	if ps := wtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, wtd.driver, _spec)
}

// WidgetTypeDeleteOne is the builder for deleting a single WidgetType entity.
type WidgetTypeDeleteOne struct {
	wtd *WidgetTypeDelete
}

// Exec executes the deletion query.
func (wtdo *WidgetTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := wtdo.wtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{widgettype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wtdo *WidgetTypeDeleteOne) ExecX(ctx context.Context) {
	wtdo.wtd.ExecX(ctx)
}
