// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Widget is the predicate function for widget builders.
type Widget func(*sql.Selector)

// WidgetType is the predicate function for widgettype builders.
type WidgetType func(*sql.Selector)
